"""remove createat

Revision ID: 7b4a8a33a17d
Revises: 70b5f42a4443
Create Date: 2025-06-12 15:03:45.427481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4a8a33a17d'
down_revision: Union[str, None] = '70b5f42a4443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rolemaster', 'modified_by')
    op.drop_column('rolemaster', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rolemaster', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('rolemaster', sa.Column('modified_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
