"""Add unique constraint to role_mapping

Revision ID: 90faeaf1d51d
Revises: e504afd9e0a5
Create Date: 2025-07-07 10:29:34.194939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90faeaf1d51d'
down_revision: Union[str, None] = 'e504afd9e0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_role', 'rolemapping', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_role', 'rolemapping', type_='unique')
    # ### end Alembic commands ###
