FROM python:3.11-slim

RUN mkdir /app

WORKDIR /app

COPY requirements.txt .
# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy rest of the code and init script
COPY . .

CMD ["python", "worker.py"]
